services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5000 run:app
    volumes:
      - .:/app
